[org/gnome/desktop/interface]
accent-color='green'
clock-show-seconds=true
clock-show-weekday=true
color-scheme='prefer-dark'
enable-hot-corners=false
gtk-theme='adw-gtk3-dark'
icon-theme='Adwaita'
gtk-enable-primary-paste=true

[org/gnome/desktop/calendar]
show-weekdate=true

[org/gnome/mutter]
focus-change-on-pointer-rest=false
workspaces-only-on-primary=false

[org/gnome/shell/app-switcher]
current-workspace-only=true

[org/gnome/desktop/wm/preferences]
focus-mode='sloppy'
