[org/gnome/settings-daemon/plugins/media-keys]
calculator=['<Super>c']
control-center=['<Super>i']
custom-keybindings=['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom2/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom3/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom4/']
home=['<Super>e']
logout=['<Shift><Super>l']
reboot=['<Control><Super>r']
shutdown=['<Control><Super>p']
www=['<Super>b']

[org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0]
binding='<Super>s'
command='systemctl suspend'
name='Suspend'

[org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1]
binding='<Control><Alt>Return'
command='kgx'
name='Terminal'

[org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom2]
binding='<Shift><Control>Escape'
command='kgx -- btop'
name='btop'

[org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom3]
binding='<Control><Alt>0'
command='change-theme'
name='Change theme'

[org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom4]
binding='<Super>t'
command='flatpak run dev.zed.Zed'
name='Zed'

[org/gnome/desktop/wm/keybindings]
close=['<Super>q']
move-to-workspace-1=['<Shift><Super>1']
move-to-workspace-2=['<Shift><Super>2']
move-to-workspace-3=['<Shift><Super>3']
move-to-workspace-4=['<Shift><Super>4']
panel-run-dialog=['<Super>r']
switch-to-workspace-1=['<Super>1']
switch-to-workspace-2=['<Super>2']
switch-to-workspace-3=['<Super>3']
switch-to-workspace-4=['<Super>4']

[org/gnome/shell/keybindings]
switch-to-application-1=@as []
switch-to-application-2=@as []
switch-to-application-3=@as []
switch-to-application-4=@as []
toggle-message-tray=@as []
toggle-quick-settings=@as []
